name = "drive-v1"
type = "webpack"
workers_dev = true
account_id = "86079e9e0b50074b4b0fd34503c41af3"
zone_id = "6aa6ad2ac4f0e88b935b3ca8d1c2511b"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "55b0fc4e288a465fb225421f2af5d445", id = "09b0cf433f394b309d35d1ff3bd0bf39" }
]

[env.staging]
name = "drive-staging"
